/**
 * NUS Script Parser
 *
 * Parses .nus script files used by the original NUS Downloader for batch downloads.
 *
 * Format: one title per line
 *   {titleID} {versionHexBytes}
 *
 * Example:
 *   0000000100000009 040A
 *   000000010000000c 020E
 *
 * Lines starting with # or // are comments.
 * Empty lines are skipped.
 */

/**
 * Parse a .nus script file.
 *
 * @param {string} text - Raw script content
 * @returns {Array<{titleId: string, version: number, line: number}>}
 */
export function parseNUSScript(text) {
  const lines = text.split(/\r?\n/);
  const entries = [];

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) continue;

    const parts = trimmed.split(/\s+/);
    if (parts.length < 2) continue;

    const titleId = parts[0].toLowerCase();
    if (!/^[0-9a-f]{16}$/.test(titleId)) continue;

    const versionHex = parts[1];
    const version = parseInt(versionHex, 16);

    if (isNaN(version)) continue;

    entries.push({ titleId, version, line: i + 1 });
  }

  return entries;
}

/**
 * Generate a .nus script from a list of entries.
 *
 * @param {Array<{titleId: string, version: number}>} entries
 * @returns {string}
 */
export function generateNUSScript(entries) {
  const lines = [
    '# NUS Download Script',
    '# Generated by Web NUS Downloader',
    '# Format: titleID versionHex',
    '',
  ];

  for (const entry of entries) {
    const vHex = entry.version.toString(16).padStart(4, '0').toUpperCase();
    lines.push(`${entry.titleId} ${vHex}`);
  }

  return lines.join('\n') + '\n';
}
